<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Report_PhieuGiaiPhongLoHang</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>.NETFramework,Version=v4.5.2</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Data" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="DevExpress.Charts.v21.2.Core" />
    <Reference Include="DevExpress.XtraCharts.v21.2.Wizard" />
    <Reference Include="DevExpress.XtraCharts.v21.2" />
    <Reference Include="DevExpress.Pdf.v21.2.Core" />
    <Reference Include="DevExpress.Office.v21.2.Core" />
    <Reference Include="DevExpress.RichEdit.v21.2.Core" />
    <Reference Include="DevExpress.RichEdit.v21.2.Export" />
    <Reference Include="DevExpress.Printing.v21.2.Core" />
    <Reference Include="DevExpress.PivotGrid.v21.2.Core" />
    <Reference Include="DevExpress.Sparkline.v21.2.Core" />
    <Reference Include="DevExpress.CodeParser.v21.2" />
    <Reference Include="DevExpress.XtraPrinting.v21.2" />
    <Reference Include="DevExpress.Utils.v21.2.UI" />
    <Reference Include="DevExpress.XtraReports.v21.2.Extensions" />
    <Reference Include="DevExpress.XtraReports.v21.2" />
    <Reference Include="ServerShared" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Data" />
    <Reference Include="DevExpress.Data.v21.2" />
  </ItemGroup>
</Project>